// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function YueAdaptLyrics(arg1, arg2) {
  return window['go']['main']['App']['YueAdaptLyrics'](arg1, arg2);
}

export function YueAddReference() {
  return window['go']['main']['App']['YueAddReference']();
}

export function YueAnalyzeJob(arg1) {
  return window['go']['main']['App']['YueAnalyzeJob'](arg1);
}

export function YueApplyDsp(arg1, arg2, arg3) {
  return window['go']['main']['App']['YueApplyDsp'](arg1, arg2, arg3);
}

export function YueAudioState() {
  return window['go']['main']['App']['YueAudioState']();
}

export function YueAudioURL(arg1, arg2) {
  return window['go']['main']['App']['YueAudioURL'](arg1, arg2);
}

export function YueCancelJob(arg1) {
  return window['go']['main']['App']['YueCancelJob'](arg1);
}

export function YueContinueJob(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['YueContinueJob'](arg1, arg2, arg3, arg4, arg5);
}

export function YueCopilot(arg1) {
  return window['go']['main']['App']['YueCopilot'](arg1);
}

export function YueCorpusAddTracks(arg1) {
  return window['go']['main']['App']['YueCorpusAddTracks'](arg1);
}

export function YueCorpusBuild(arg1) {
  return window['go']['main']['App']['YueCorpusBuild'](arg1);
}

export function YueCorpusCreate(arg1) {
  return window['go']['main']['App']['YueCorpusCreate'](arg1);
}

export function YueCorpusGet(arg1) {
  return window['go']['main']['App']['YueCorpusGet'](arg1);
}

export function YueCorpusList() {
  return window['go']['main']['App']['YueCorpusList']();
}

export function YueCorpusTracks(arg1) {
  return window['go']['main']['App']['YueCorpusTracks'](arg1);
}

export function YueDeleteJob(arg1) {
  return window['go']['main']['App']['YueDeleteJob'](arg1);
}

export function YueDspChains() {
  return window['go']['main']['App']['YueDspChains']();
}

export function YueDspPreview(arg1, arg2, arg3) {
  return window['go']['main']['App']['YueDspPreview'](arg1, arg2, arg3);
}

export function YueDspVariantDelete(arg1, arg2) {
  return window['go']['main']['App']['YueDspVariantDelete'](arg1, arg2);
}

export function YueDspVariants(arg1) {
  return window['go']['main']['App']['YueDspVariants'](arg1);
}

export function YueEnsureMp3(arg1) {
  return window['go']['main']['App']['YueEnsureMp3'](arg1);
}

export function YueGetServerURL() {
  return window['go']['main']['App']['YueGetServerURL']();
}

export function YueImportTrack() {
  return window['go']['main']['App']['YueImportTrack']();
}

export function YueJobAbcText(arg1, arg2) {
  return window['go']['main']['App']['YueJobAbcText'](arg1, arg2);
}

export function YueJobLyrics(arg1) {
  return window['go']['main']['App']['YueJobLyrics'](arg1);
}

export function YueJobPeaks(arg1, arg2, arg3) {
  return window['go']['main']['App']['YueJobPeaks'](arg1, arg2, arg3);
}

export function YueJobPreview(arg1, arg2, arg3) {
  return window['go']['main']['App']['YueJobPreview'](arg1, arg2, arg3);
}

export function YueJobScore(arg1) {
  return window['go']['main']['App']['YueJobScore'](arg1);
}

export function YueJobSpectrumPNG(arg1, arg2) {
  return window['go']['main']['App']['YueJobSpectrumPNG'](arg1, arg2);
}

export function YueJobStems(arg1) {
  return window['go']['main']['App']['YueJobStems'](arg1);
}

export function YuePlanCheck(arg1, arg2, arg3) {
  return window['go']['main']['App']['YuePlanCheck'](arg1, arg2, arg3);
}

export function YueJobTones(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['YueJobTones'](arg1, arg2, arg3, arg4);
}

export function YueJobs() {
  return window['go']['main']['App']['YueJobs']();
}

export function YueMakeMinus(arg1, arg2) {
  return window['go']['main']['App']['YueMakeMinus'](arg1, arg2);
}

export function YueMakeStems(arg1) {
  return window['go']['main']['App']['YueMakeStems'](arg1);
}

export function YueOllamaModels(arg1) {
  return window['go']['main']['App']['YueOllamaModels'](arg1);
}

export function YueOpenExternal(arg1, arg2) {
  return window['go']['main']['App']['YueOpenExternal'](arg1, arg2);
}

export function YueOpenURL(arg1) {
  return window['go']['main']['App']['YueOpenURL'](arg1);
}

export function YuePlan(arg1) {
  return window['go']['main']['App']['YuePlan'](arg1);
}

export function YuePlayAudio(arg1) {
  return window['go']['main']['App']['YuePlayAudio'](arg1);
}

export function YuePlayFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['YuePlayFile'](arg1, arg2, arg3);
}

export function YueRebuildSections(arg1, arg2) {
  return window['go']['main']['App']['YueRebuildSections'](arg1, arg2);
}

export function YueRecognizeLyricsFile() {
  return window['go']['main']['App']['YueRecognizeLyricsFile']();
}

export function YueReferences() {
  return window['go']['main']['App']['YueReferences']();
}

export function YueSaveAudio(arg1, arg2) {
  return window['go']['main']['App']['YueSaveAudio'](arg1, arg2);
}

export function YueSeekAudio(arg1) {
  return window['go']['main']['App']['YueSeekAudio'](arg1);
}

export function YueSetHead(arg1, arg2) {
  return window['go']['main']['App']['YueSetHead'](arg1, arg2);
}

export function YueSetServerURL(arg1) {
  return window['go']['main']['App']['YueSetServerURL'](arg1);
}

export function YueSetVolume(arg1) {
  return window['go']['main']['App']['YueSetVolume'](arg1);
}

export function YueSetWorkerConfig(arg1) {
  return window['go']['main']['App']['YueSetWorkerConfig'](arg1);
}

export function YueStatus() {
  return window['go']['main']['App']['YueStatus']();
}

export function YueStopAudio() {
  return window['go']['main']['App']['YueStopAudio']();
}

export function YueSubmit(arg1) {
  return window['go']['main']['App']['YueSubmit'](arg1);
}

export function YueSubmitFan(arg1, arg2) {
  return window['go']['main']['App']['YueSubmitFan'](arg1, arg2);
}

export function YueSubmitOverdub(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['YueSubmitOverdub'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function YueToggleAudio() {
  return window['go']['main']['App']['YueToggleAudio']();
}

export function YueTranscribeFile() {
  return window['go']['main']['App']['YueTranscribeFile']();
}

export function YueTranslate(arg1) {
  return window['go']['main']['App']['YueTranslate'](arg1);
}

export function YueVariantToTrack(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['YueVariantToTrack'](arg1, arg2, arg3, arg4);
}

export function YueVocalContour(arg1, arg2, arg3) {
  return window['go']['main']['App']['YueVocalContour'](arg1, arg2, arg3);
}

export function YueVoiceCreate(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['YueVoiceCreate'](arg1, arg2, arg3, arg4);
}

export function YueVoiceDelete(arg1) {
  return window['go']['main']['App']['YueVoiceDelete'](arg1);
}

export function YueVoices() {
  return window['go']['main']['App']['YueVoices']();
}

export function YueWorkerConfig() {
  return window['go']['main']['App']['YueWorkerConfig']();
}
