// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {yue} from '../models';
import {main} from '../models';
import {dsp} from '../models';

export function YueAddReference():Promise<yue.Reference>;

export function YueAnalyzeJob(arg1:number):Promise<Record<string, any>>;

export function YueApplyDsp(arg1:number,arg2:string,arg3:Record<string, number>):Promise<yue.DspVariant>;

export function YueAudioState():Promise<main.YuePlayerState>;

export function YueAudioURL(arg1:number,arg2:string):Promise<string>;

export function YueCancelJob(arg1:number):Promise<boolean>;

export function YueCopilot(arg1:yue.CopilotParams):Promise<yue.CopilotResult>;

export function YueCorpusAddTracks(arg1:number):Promise<number>;

export function YueCorpusBuild(arg1:number):Promise<Record<string, any>>;

export function YueCorpusCreate(arg1:string):Promise<number>;

export function YueCorpusGet(arg1:number):Promise<Record<string, any>>;

export function YueCorpusList():Promise<Array<yue.Corpus>>;

export function YueCorpusTracks(arg1:number):Promise<Array<Record<string, any>>>;

export function YueDeleteJob(arg1:number):Promise<boolean>;

export function YueDspChains():Promise<Array<dsp.Chain>>;

export function YueDspVariants(arg1:number):Promise<Array<yue.DspVariant>>;

export function YueGetServerURL():Promise<string>;

export function YueJobPreview(arg1:number,arg2:number,arg3:number):Promise<Record<string, any>>;

export function YueJobScore(arg1:number):Promise<Record<string, any>>;

export function YueJobStems(arg1:number):Promise<Array<Record<string, any>>>;

export function YueJobs():Promise<Array<yue.Job>>;

export function YueMakeStems(arg1:number):Promise<Record<string, any>>;

export function YueOpenExternal(arg1:number,arg2:string):Promise<void>;

export function YueOpenURL(arg1:string):Promise<void>;

export function YuePlan(arg1:yue.PlanParams):Promise<yue.PlanResult>;

export function YuePlayAudio(arg1:number):Promise<void>;

export function YuePlayFile(arg1:number,arg2:string,arg3:number):Promise<void>;

export function YueReferences():Promise<Array<yue.Reference>>;

export function YueSaveAudio(arg1:number,arg2:string):Promise<string>;

export function YueSetServerURL(arg1:string):Promise<void>;

export function YueStatus():Promise<yue.HealthInfo>;

export function YueStopAudio():Promise<void>;

export function YueSubmit(arg1:yue.SubmitParams):Promise<number>;

export function YueSubmitFan(arg1:yue.SubmitParams,arg2:number):Promise<Array<number>>;

export function YueSubmitOverdub(arg1:number,arg2:string,arg3:number):Promise<number>;

export function YueToggleAudio():Promise<void>;

export function YueTranscribeFile():Promise<yue.TranscribeResult>;

export function YueTranslate(arg1:string):Promise<yue.TranslateResult>;
