// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {yue} from '../models';
import {dsp} from '../models';
import {main} from '../models';
import {studio} from '../models';

export function YueAdaptLyrics(arg1:string,arg2:string):Promise<yue.LyricsResult>;

export function YueAddReference():Promise<yue.Reference>;

export function YueAnalyzeJob(arg1:number):Promise<Record<string, any>>;

export function YueApplyDsp(arg1:number,arg2:string,arg3:Record<string, number>):Promise<yue.DspVariant>;

export function YueApplyFx(arg1:number,arg2:yue.FxRequest):Promise<yue.DspVariant>;

export function YueApplySoundPreset(arg1:number,arg2:number):Promise<number>;

export function YueApplySoundPresetWith(arg1:number,arg2:yue.SoundPreset):Promise<number>;

export function YueApplySteps(arg1:number,arg2:Array<dsp.Step>,arg3:string):Promise<yue.DspVariant>;

export function YueAudioState():Promise<main.YuePlayerState>;

export function YueAudioURL(arg1:number,arg2:string):Promise<string>;

export function YueCancelJob(arg1:number):Promise<boolean>;

export function YueContinueJob(arg1:number,arg2:number,arg3:number,arg4:string,arg5:string):Promise<number>;

export function YueCopilot(arg1:yue.CopilotParams):Promise<yue.CopilotResult>;

export function YueCorpusAddTracks(arg1:number):Promise<number>;

export function YueCorpusBuild(arg1:number):Promise<Record<string, any>>;

export function YueCorpusCreate(arg1:string):Promise<number>;

export function YueCorpusGet(arg1:number):Promise<Record<string, any>>;

export function YueCorpusList():Promise<Array<yue.Corpus>>;

export function YueCorpusTracks(arg1:number):Promise<Array<Record<string, any>>>;

export function YueDeleteJob(arg1:number):Promise<boolean>;

export function YueDspChains():Promise<Array<dsp.Chain>>;

export function YueDspPresets():Promise<Array<dsp.Preset>>;

export function YueDspVariantDelete(arg1:number,arg2:string):Promise<boolean>;

export function YueDspVariants(arg1:number):Promise<Array<yue.DspVariant>>;

export function YueEnsureMp3(arg1:number):Promise<Record<string, any>>;

export function YueFxAssets():Promise<Record<string, any>>;

export function YueFxPreview(arg1:number,arg2:string,arg3:Array<dsp.Step>,arg4:number,arg5:number,arg6:string):Promise<studio.PreviewResult>;

export function YueGetServerURL():Promise<string>;

export function YueImportTrack():Promise<Record<string, any>>;

export function YueInstallFxKit(arg1:string):Promise<Record<string, any>>;

export function YueJobAbcText(arg1:number,arg2:string):Promise<string>;

export function YueJobGrid(arg1:number,arg2:number,arg3:number):Promise<yue.BeatGrid>;

export function YueJobLyrics(arg1:number):Promise<yue.LyricsResult>;

export function YueJobPeaks(arg1:number,arg2:string,arg3:number):Promise<Record<string, any>>;

export function YueJobPreview(arg1:number,arg2:number,arg3:number):Promise<Record<string, any>>;

export function YueJobScore(arg1:number):Promise<Record<string, any>>;

export function YueJobSpectrumPNG(arg1:number,arg2:string):Promise<Array<number>>;

export function YueJobStems(arg1:number):Promise<Array<Record<string, any>>>;

export function YueJobTones(arg1:number,arg2:number,arg3:number,arg4:string):Promise<Array<yue.Tone>>;

export function YueJobs():Promise<Array<yue.Job>>;

export function YueMakeMinus(arg1:number,arg2:Array<string>):Promise<Record<string, any>>;

export function YueMakeStems(arg1:number):Promise<Record<string, any>>;

export function YueOllamaModels(arg1:string):Promise<Record<string, any>>;

export function YueOpenExternal(arg1:number,arg2:string):Promise<void>;

export function YueOpenURL(arg1:string):Promise<void>;

export function YuePlan(arg1:yue.PlanParams):Promise<yue.PlanResult>;

export function YuePlanCheck(arg1:number,arg2:string,arg3:number):Promise<yue.PlanCheck>;

export function YuePlayAudio(arg1:number):Promise<void>;

export function YuePlayFile(arg1:number,arg2:string,arg3:number):Promise<void>;

export function YuePlayPreview(arg1:number,arg2:string,arg3:string,arg4:number):Promise<void>;

export function YueRebuildSections(arg1:number,arg2:Array<studio.SectionSpec>):Promise<studio.RebuildResult>;

export function YueRecognizeLyricsFile():Promise<yue.LyricsResult>;

export function YueReferences():Promise<Array<yue.Reference>>;

export function YueRenameJob(arg1:number,arg2:string):Promise<yue.Job>;

export function YueRetryJob(arg1:number):Promise<void>;

export function YueSaveAudio(arg1:number,arg2:string):Promise<string>;

export function YueSeekAudio(arg1:number):Promise<void>;

export function YueSetHead(arg1:number,arg2:number):Promise<void>;

export function YueSetJobFolder(arg1:number,arg2:string):Promise<yue.Job>;

export function YueSetServerURL(arg1:string):Promise<void>;

export function YueSetVolume(arg1:number):Promise<void>;

export function YueSetWorkerConfig(arg1:Record<string, any>):Promise<void>;

export function YueSoundPresetCreate(arg1:yue.SoundPreset):Promise<yue.SoundPreset>;

export function YueSoundPresetDelete(arg1:number):Promise<void>;

export function YueSoundPresetRetry(arg1:number,arg2:number):Promise<void>;

export function YueSoundPresetUpdate(arg1:number,arg2:yue.SoundPreset):Promise<yue.SoundPreset>;

export function YueSoundPresets():Promise<Array<yue.SoundPreset>>;

export function YueSplice(arg1:number,arg2:Array<studio.SplicePart>,arg3:number):Promise<yue.DspVariant>;

export function YueStats():Promise<yue.StatsInfo>;

export function YueStatus():Promise<yue.HealthInfo>;

export function YueStopAudio():Promise<void>;

export function YueSubmit(arg1:yue.SubmitParams):Promise<number>;

export function YueSubmitFan(arg1:yue.SubmitParams,arg2:number):Promise<Array<number>>;

export function YueSubmitOverdub(arg1:number,arg2:string,arg3:string,arg4:number,arg5:string,arg6:number):Promise<number>;

export function YueToggleAudio():Promise<void>;

export function YueTranscribeFile():Promise<yue.TranscribeResult>;

export function YueTranscribeJob(arg1:number):Promise<Record<string, any>>;

export function YueTranslate(arg1:string):Promise<yue.TranslateResult>;

export function YueUploadFxAsset(arg1:string):Promise<Record<string, any>>;

export function YueVariantToTrack(arg1:number,arg2:string,arg3:string,arg4:number):Promise<number>;

export function YueVocalContour(arg1:number,arg2:number,arg3:number):Promise<yue.VocalContour>;

export function YueVoiceConvert(arg1:number,arg2:yue.VoiceParams):Promise<number>;

export function YueVoiceCreate(arg1:string,arg2:number,arg3:string,arg4:number):Promise<number>;

export function YueVoiceDelete(arg1:number):Promise<boolean>;

export function YueVoices():Promise<Array<yue.Voice>>;

export function YueVolumeEnvelope(arg1:number,arg2:string,arg3:Array<dsp.EnvPoint>):Promise<yue.DspVariant>;

export function YueWorkerConfig():Promise<Record<string, any>>;
