import {
  YueStatus, YueJobs, YueSubmit, YueSubmitFan, YuePlan, YueCancelJob, YueAudioURL,
  YueOpenExternal, YueSaveAudio, YueOpenURL, YueGetServerURL, YueSetServerURL,
  YueWorkerConfig, YueSetWorkerConfig, YueOllamaModels,
  YueAnalyzeJob, YueReferences, YueAddReference, YueDspChains, YueApplyDsp, YueDspPreview, YueDspVariants,
  YueCopilot,
  YueTranscribeFile, YueImportTrack, YueEnsureMp3, YueJobScore, YueJobPreview, YueSubmitOverdub,
  YueMakeStems, YueJobStems, YueMakeMinus,
  YueCorpusCreate, YueCorpusAddTracks, YueCorpusBuild, YueCorpusList, YueCorpusGet, YueCorpusTracks,
  YuePlayFile, YueToggleAudio, YueStopAudio, YueSeekAudio, YueSetVolume, YuePlayAudio, YueAudioState, YueTranslate, YueDeleteJob,
} from './wailsjs/go/main/App'

export const api = {
  status: () => YueStatus(),
  jobs: () => YueJobs(),
  submit: (p) => YueSubmit(p),
  submitFan: (p, n) => YueSubmitFan(p, n),
  plan: (p) => YuePlan(p),
  cancel: (id) => YueCancelJob(id),
  deleteJob: (id) => YueDeleteJob(id),
  audioURL: (id, file) => YueAudioURL(id, file),
  openExternal: (id, file) => YueOpenExternal(id, file),
  openURL: (url) => YueOpenURL(url),
  saveAudio: (id, file) => YueSaveAudio(id, file),
  getServerURL: () => YueGetServerURL(),
  setServerURL: (url) => YueSetServerURL(url),
  workerConfig: () => YueWorkerConfig(),
  setWorkerConfig: (cfg) => YueSetWorkerConfig(cfg),
  ollamaModels: (url) => YueOllamaModels(url || ''),
  analyze: (id) => YueAnalyzeJob(id),
  references: () => YueReferences(),
  addReference: () => YueAddReference(),
  dspChains: () => YueDspChains(),
  applyDsp: (id, chain, params) => YueApplyDsp(id, chain, params),
  dspVariants: (id) => YueDspVariants(id),
  dspPreview: (id, chain, params) => YueDspPreview(id, chain, params),
  copilot: (p) => YueCopilot(p),
  // v2/v3
  transcribeFile: () => YueTranscribeFile(),
  importTrack: () => YueImportTrack(),
  ensureMp3: (id) => YueEnsureMp3(id),
  jobScore: (id) => YueJobScore(id),
  jobPreview: (id, from, to) => YueJobPreview(id, from, to),
  submitOverdub: (id, style, gain) => YueSubmitOverdub(id, style, gain),
  makeStems: (id) => YueMakeStems(id),
  jobStems: (id) => YueJobStems(id),
  makeMinus: (id, exclude) => YueMakeMinus(id, exclude || []),
  corpusCreate: (name) => YueCorpusCreate(name),
  corpusAddTracks: (id) => YueCorpusAddTracks(id),
  corpusBuild: (id) => YueCorpusBuild(id),
  corpusList: () => YueCorpusList(),
  corpusGet: (id) => YueCorpusGet(id),
  corpusTracks: (id) => YueCorpusTracks(id),
  playFile: (id, file, dur) => YuePlayFile(id, file, dur),
  playAudio: (id) => YuePlayAudio(id),
  translate: (text) => YueTranslate(text),
  stopAudio: () => YueStopAudio(),
  toggleAudio: () => YueToggleAudio(),
  seekAudio: (sec) => YueSeekAudio(sec),
  audioState: () => YueAudioState(),
  setVolume: (v) => YueSetVolume(v),
}
