// Словарные данные формы стиля: подсказки полей (ru → en для YuE),
// метаданные полей, заготовки партий овердаба, режимы длительности.

export const slotKeys = ['language', 'genre', 'rhythm', 'guitars', 'keys', 'vocals', 'mood', 'production']

export const slotOptions = {
  language: [
    ['Русский', 'Russian'], ['English', 'English'],
    ['Корейский', 'Korean'], ['Японский', 'Japanese'], ['Китайский', 'Chinese (Mandarin)'],
    ['Немецкий', 'German'], ['Испанский', 'Spanish'], ['Французский', 'French'],
    ['Итальянский', 'Italian'], ['Португальский', 'Portuguese'],
    ['Турецкий', 'Turkish'], ['Арабский', 'Arabic'], ['Хинди', 'Hindi'],
    ['Латынь', 'Latin'], ['Санскрит', 'Sanskrit'], ['Українська', 'Ukrainian'],
  ],
  genre: [
    ['1960-е психоделический блюз-рок', '1960s psychedelic blues rock'],
    ['1980-е сибирский андеграунд, панк-энергия поверх пост-панк тоски', '1980s Siberian underground rock, punk energy over post-punk gloom'],
    ['1980-е сибирский андеграунд, медленный минорный отпевальный рок', '1980s Siberian underground rock, slow minor key dirge'],
    ['acid folk', 'acid folk'],
    ['агрессивный пост-панк', 'aggressive post-punk'],
    ['эмбиент', 'ambient'],
    ['арт-панк', 'art punk'],
    ['атмосферный блэк-метал', 'atmospheric black metal'],
    ['баллада', 'ballad'],
    ['бибоп', 'bebop'],
    ['унылый лоу-фай сибирский панк', 'bleak lo-fi Siberian punk'],
    ['унылая медленная серая песня', 'bleak slow grey song'],
    ['блюграсс', 'bluegrass'],
    ['блюз', 'blues'],
    ['блюз-рок', 'blues rock'],
    ['босса-нова', 'bossa nova'],
    ['брейкбит', 'breakbeat'],
    ['брит-поп', 'britpop'],
    ['кельтский фолк', 'celtic folk'],
    ['шансон', 'chanson'],
    ['chillwave', 'chillwave'],
    ['чиптюн', 'chiptune'],
    ['чиптюн-панк (нинтендо-панк)', 'chiptune punk, 8-bit punk'],
    ['колдвейв', 'coldwave'],
    ['кантри', 'country'],
    ['кантри-баллада', 'country ballad'],
    ['краст-панк', 'crust punk'],
    ['дарк-эмбиент', 'dark ambient'],
    ['дарк-кабаре', 'dark cabaret'],
    ['дарк-фолк', 'dark folk'],
    ['мрачный пост-панк', 'dark post-punk'],
    ['дарквейв', 'darkwave'],
    ['дэт-метал', 'death metal'],
    ['дет-рок', 'deathrock'],
    ['диско', 'disco'],
    ['дум-метал', 'doom metal'],
    ['даунтемпо', 'downtempo'],
    ['дрон', 'drone'],
    ['данжен-синт', 'dungeon synth'],
    ['даб', 'dub'],
    ['даб-техно', 'dub techno'],
    ['электропанк', 'electropunk'],
    ['евродэнс 1997', 'eurodance 1997'],
    ['экспериментальный нойз', 'experimental noise'],
    ['фламенко', 'flamenco'],
    ['фолк-рок с мировой музыкой', 'folk rock, world music shades'],
    ['фьюнерал-дум', 'funeral doom'],
    ['фанк', 'funk'],
    ['гаражный рок', 'garage rock'],
    ['глэм-рок', 'glam rock'],
    ['госпел', 'gospel'],
    ['готик-метал', 'gothic metal'],
    ['готический пост-панк с диким панком', 'gothic post-punk gloom with raw punk energy'],
    ['грайм', 'grime'],
    ['грайндкор', 'grindcore'],
    ['гранж', 'grunge'],
    ['хард-рок', 'hard rock'],
    ['хардкор-панк', 'hardcore punk'],
    ['хэви-метал', 'heavy metal'],
    ['хип-хоп', 'hip-hop'],
    ['хорроркор', 'horrorcore'],
    ['хаус', 'house'],
    ['хайперпоп', 'hyperpop'],
    ['IDM', 'idm'],
    ['инди-фолк', 'indie folk'],
    ['инди-поп', 'indie pop'],
    ['индастриал', 'industrial'],
    ['индастриал-метал', 'industrial metal'],
    ['индастриал-рок', 'industrial rock'],
    ['джаз-фьюжн', 'jazz fusion'],
    ['джаз-нуар', 'jazz noir'],
    ['клезмер', 'klezmer'],
    ['клезмер-панк', 'klezmer punk'],
    ['краут-рок', 'krautrock'],
    ['латино-рок', 'latin rock'],
    ['мэт-рок', 'math rock'],
    ['мелодичный дэт-метал', 'melodic death metal'],
    ['мелодичный хардкор', 'melodic hardcore'],
    ['моутаун', 'motown'],
    ['мистический арт-рок', 'mystic art rock'],
    ['неоклассический дарквейв', 'neoclassical darkwave'],
    ['неофолк', 'neofolk'],
    ['неофолк-баллада, модальный минор', 'neofolk ballad, modal minor'],
    ['нью-романтик', 'new romantic'],
    ['новая волна', 'new wave'],
    ['нинтендокор (чиптюн + метал)', 'nintendocore'],
    ['нойз-рок', 'noise rock'],
    ['ну-диско', 'nu disco'],
    ['ню-метал', 'nu metal'],
    ['пост-боп', 'post-bop'],
    ['пост-гранж', 'post-grunge'],
    ['пост-хардкор', 'post-hardcore'],
    ['пост-метал', 'post-metal'],
    ['пост-панк', 'post-punk'],
    ['пост-рок, атмосферные инструментальные волны', 'post-rock, atmospheric instrumental waves'],
    ['пауэр-баллада', 'power ballad'],
    ['пауэр-метал', 'power metal'],
    ['пауэр-поп', 'power pop'],
    ['прогрессив-метал', 'progressive metal'],
    ['прогрессив-рок', 'progressive rock'],
    ['психодел-фолк', 'psychedelic folk'],
    ['психодел-рок', 'psychedelic rock'],
    ['сайкобилли', 'psychobilly'],
    ['панк', 'punk'],
    ['панк-блюз', 'punk blues'],
    ['ритм-н-блюз, соул', 'r&b soul'],
    ['рэгтайм', 'ragtime'],
    ['рэп-рок', 'rap rock'],
    ['регги', 'reggae'],
    ['реггетон', 'reggaeton'],
    ['ритмичный нойз', 'rhythmic noise'],
    ['рокабилли', 'rockabilly'],
    ['сырой лоу-фай сибирский панк, советский андеграунд 1980-х', 'raw lo-fi Siberian punk, 1980s Soviet underground punk'],
    ['шугейз', 'shoegaze'],
    ['авторская песня', 'singer-songwriter'],
    ['ска', 'ska'],
    ['ска-панк', 'ska punk'],
    ['слакер-рок', 'slacker rock'],
    ['сладж-метал', 'sludge metal'],
    ['слоукор', 'slowcore'],
    ['саузерн-рок', 'southern rock'],
    ['спейс-рок', 'space rock'],
    ['стонер-рок', 'stoner rock'],
    ['сёрф-рок', 'surf rock'],
    ['свинг', 'swing'],
    ['синт-фанк', 'synth-funk'],
    ['синтпоп', 'synthpop'],
    ['синтвейв', 'synthwave'],
    ['новое танго', 'tango nuevo'],
    ['техничный дэт-метал', 'technical death metal'],
    ['театральный хоррор-панк', 'theatrical horror punk'],
    ['трэш-метал', 'thrash metal'],
    ['традиционный фолк', 'traditional folk'],
    ['трип-хоп', 'trip-hop'],
    ['вейпорвейв', 'vaporwave'],
    ['world fusion', 'world fusion'],
    ['яхт-рок', 'yacht rock'],
  ],
  rhythm: [
    ['медленно и спокойно', 'slow relaxed groove'],
    ['умеренно, головой в такт', 'moderate head-nodding groove'],
    ['быстро и энергично', 'fast driving beat'],
    ['ровно, как машина (драм-машина)', 'steady drum machine beat'],
    ['танцевально: ровный бум-бум', 'four-on-the-floor dance beat'],
    ['без барабанов', 'no percussion'],
    ['качающий тяжёлый бит', 'heavy grooving beat'],
    ['8-битные шумовые барабаны', '8-bit noise-channel drums'],
    ['гулкая чихающая бас-гитара впереди, драм-машина и коробочная перкуссия, быстрая короткая песня', 'booming sputtering bass guitar at the forefront, drum machine and box percussion, fast short song'],
    ['бум-бэп, качающий свинг', 'boom bap beat, head-nodding swing'],
    ['брейкбит, нарезанный фанк', 'breakbeat, chopped funk drums'],
    ['двойная бочка', 'double kick blast drums'],
    ['напористая повторяющаяся бас-линия, ровный энергичный грув', 'driving repetitive bassline, steady energetic groove'],
    ['даб-бас с космическими дилэями', 'dub bassline with spacey delays'],
    ['ди-бит', 'd-beat drumming'],
    ['этническая перкуссия', 'ethnic percussion'],
    ['быстрая панк-энергия', 'fast punk energy'],
    ['четыре-на-пол драм-машина', 'four-on-the-floor drum machine'],
    ['фанковый синкопированный грув', 'funky syncopated groove'],
    ['глитчевые IDM-биты', 'glitchy IDM beats'],
    ['хаф-тайм грув, тяжёлый снейр', 'half-time groove, heavy snare'],
    ['тяжёлый переваливающийся бас, глухие картонные барабаны', 'heavy loping bass pulse, muffled cardboard drums'],
    ['тяжёлый регги-уклон баса, картонные барабаны, средний темп', 'heavy loping reggae-leaning bass pulse, cardboard drums, mid-tempo lilt'],
    ['гипнотический грув', 'hypnotic groove'],
    ['джазовый свинг-шаффл, щётки', 'jazz swing shuffle, brushed drums'],
    ['латинская клаве, конги', 'latin clave rhythm, congas'],
    ['средний темп', 'mid-tempo'],
    ['моторик-бит (краут)', 'motorik krautrock beat'],
    ['one drop грув, тёплый круглый бас', 'one drop groove, warm round bass'],
    ['молотящие барабаны', 'pounding drums'],
    ['программные трэп-хэты, 808-бас', 'programmed trap hi-hats, 808 bass'],
    ['медленно', 'slow'],
    ['медленный дум-шаг', 'slow doom plod'],
    ['мягкие барабаны, нарастают и сходят', 'soft drums building and receding'],
    ['разреженная драм-машина, дешёвый пресет', 'sparse drum machine, cheap preset rhythm'],
    ['свинг-шаффл, ведущий райд', 'swing shuffle, ride cymbal lead'],
    ['синкопированная фанковая бас-линия', 'syncopated funky bassline'],
    ['трип-хоп бит, пыльные брейки', 'trip-hop beat, dusty breaks'],
    ['вальс 3/4', 'waltz 3/4'],
    ['маршевый снейр', 'marching snare pattern'],
  ],
  guitars: [
    ['акустика, перебор', 'fingerpicked acoustic guitar'],
    ['акустика, простые аккорды', 'simple strummed acoustic guitar'],
    ['чистая электрогитара, аккуратная', 'clean electric guitar'],
    ['грязная перегруженная электрогитара', 'heavy distorted electric guitar'],
    ['гитара играет главную мелодию', 'melodic guitar leads'],
    ['гитара воет протяжными нотами', 'wailing sustained guitar'],
    ['без гитар', 'no guitars'],
    ['акустический бой', 'acoustic guitar strum'],
    ['агрессивные заниженные перегруженные риффы', 'aggressive down-tuned distorted guitar riffs'],
    ['блюзовые гитарные фразы', 'bluesy guitar licks'],
    ['звенящая 12-струнная', 'chiming 12-string guitar'],
    ['чистые арпеджио электрогитары', 'clean electric guitar arpeggios'],
    ['чистая щипковая гитара, интимно', 'clean plucked guitar, intimate'],
    ['дешёвая перегруженная дрон-гитара', 'cheap distorted drone guitar'],
    ['дешёвая гудящая гитара', 'cheap droning guitar'],
    ['дешёвая гудящая овердрайв-гитара', 'cheap droning overdriven guitar'],
    ['дешёвая овердрайв-гитара, примитивные аккорды', 'cheap overdriven guitar, primitive chords'],
    ['дешёвая вязкая овердрайв-гитара', 'cheap sludgy overdriven guitar'],
    ['гитары в дилэях', 'delay-drenched guitars'],
    ['дважды записанные гитары по краям', 'double-tracked hard-panned guitars'],
    ['гудящая дешёвая гитара', 'droning cheap guitar'],
    ['пальцевый фолк-подхват', 'fingerpicked folk guitar'],
    ['фламенко-расцветы', 'flamenco flourishes'],
    ['фузз-стена гитар', 'fuzz wall of guitars'],
    ['арфа и акустика', 'harp and acoustic guitar'],
    ['высокий пронзительный слайд', 'high piercing slide guitar'],
    ['джангл-поп гитары', 'jangle pop guitars'],
    ['металлические лязгающие гитары', 'metallic clangorous guitars'],
    ['сёрф-гитара с пружинным ревером', 'surf guitar with spring reverb'],
    ['оффбит-скэнк гитара', 'offbeat skank guitar'],
    ['педал-стил плачет', 'pedal steel guitar weep'],
    ['пауэр-аккорды, глухое чередование', 'power chords, palm-muted chug'],
    ['сырые овердрайв-гитары', 'raw overdriven guitars'],
    ['слайд-гитара', 'slide guitar lines'],
    ['стаккато арпеджио', 'staccato arpeggiated guitars'],
    ['тремоло-гитара', 'tremolo-picked guitar'],
    ['сдвоенные гитарные гармонии', 'twin guitar harmonies'],
    ['стена мерцающих реверб-гитар', 'wall of shimmering reverb guitars'],
  ],
  keys: [
    ['рояль', 'grand piano'],
    ['старое пианино, чуть расстроенное', 'detuned upright piano'],
    ['орган как в 60-х', 'Hammond organ'],
    ['синтезатор-подклад (фон)', 'warm synth pad'],
    ['скрипки / струнные', 'string section'],
    ['флейта', 'airy flute melody'],
    ['яркий синт-лид-хук', 'bright synth lead hook'],
    ['8-битный квадратный лид (NES)', '8-bit NES square-wave lead melodies'],
    ['блёстки челесты', 'celesta sparkle'],
    ['хаотичные скретчи', 'chaotic turntable scratches'],
    ['расстроенное прямое пианино', 'detuned upright piano'],
    ['фолк-аккордеонные акценты', 'folk accordion accents'],
    ['гейм-бой арпеджио', 'Game Boy chiptune arpeggios'],
    ['блёстки глокеншпиля', 'glockenspiel twinkle'],
    ['Хэммонд-орган', 'Hammond organ'],
    ['Хэммонд пузырит', 'Hammond organ bubbles'],
    ['клавесин', 'harpsichord'],
    ['мелодика', 'melodica'],
    ['музыкальная шкатулка', 'music box plucks'],
    ['меллотрон-флейты', 'mellotron flutes'],
    ['Родес', 'Rhodes electric piano'],
    ['пэд струнного квартета', 'string quartet pad'],
    ['вывания терменвокса', 'theremin wails'],
    ['винтажные аналоговые синт-пэды', 'vintage analog synth pads'],
    ['винтажное электропианино, аккорды', 'vintage electric piano chords'],
    ['тёплый аналоговый пэд', 'warm analog synth pad'],
    ['деревянная флейта', 'wooden flute'],
    ['вурлитцер-удары', 'wurlitzer stabs'],
  ],
  vocals: [
    ['без голоса, только инструменты', 'instrumental, no vocals'],
    ['мужской, тихо и близко', 'soft intimate male vocals'],
    ['мужской, грубый, на разрыв', 'raspy powerful male vocals'],
    ['женский, нежный', 'tender female vocals'],
    ['женский, сильный, с характером', 'powerful soulful female vocals'],
    ['полуразговор, не поёт', 'half-spoken deadpan vocals'],
    ['хор поёт вместе', 'group chant vocals, unison'],
    ['низкий мужской, размеренно', 'deep resonant baritone vocals'],
    ['воздушный эфирный женский вокал', 'airy ethereal female vocals'],
    ['ангельский хор на бэках', 'angelic choir backing'],
    ['андрогинный воздушный вокал', 'androgynous airy vocals'],
    ['цепкий радостный мужской вокал', 'catchy cheerful male vocals'],
    ['детский женский вокал', 'childlike female vocals'],
    ['хор поёт в унисон', 'choir chant in unison'],
    ['депрессивный баритон', 'deadpan baritone male vocals'],
    ['отчаянный хриплый мужской вокал', 'desperate raspy male vocals'],
    ['угрюмый вокал с перегруженным клиппингующим микрофоном', 'dour male vocals with overdriven microphone clipping'],
    ['утопленный мужской вокал на грани срыва, монотонная декламация, гэнг-крики на бэках', 'drowned buried male vocals on the verge of breaking, monotone incantation delivery, gang shout backing vocals'],
    ['дуэт мужской и женский', 'duet male and female vocals'],
    ['мужской фальцет', 'falsetto male vocals'],
    ['плоский низкий полуречитатив, депрессивная подача, утоплен в ленточном шуме', 'flat low half-spoken male vocals, deadpan delivery buried in tape noise'],
    ['плоский монотонный низкий мужской голос, полуречитатив, отстранённая подача, вокал в шуме ленты', 'flat monotonous low male voice, half-spoken deadpan singing, detached emotionless delivery, vocals buried in tape noise'],
    ['полуречитативный харизматичный мужской баритон', 'half-spoken charismatic male baritone'],
    ['гортанный дэт-гроул', 'guttural death growls'],
    ['высокий надтреснутый мужской вокал на грани слёз', 'high strained male vocals, on the verge of tears'],
    ['надтреснутый любительский вокал, без автотюна', 'high cracked amateur male vocals, off-key, no autotune, no vocal runs, unpolished raw singing'],
    ['дикое немелодичное пение, срывы', 'wild tuneless singing, voice cracking, off-pitch, no autotune, no melisma'],
    ['любительский голос без обработки', 'untrained amateur voice, no vocal processing, dry unpolished delivery'],
    ['анти-поп подача', 'no pop vocal runs, no autotune, no modern production, plain blunt singing'],
    ['хриплый, отчаянный, срывается на крик', 'raspy desperate male vocals, cracked voice, screamed chorus'],
    ['мягкий, расслабленный, с хрипотцой', 'laid-back soulful raspy male vocals, relaxed delivery'],
    ['расслабленный соуловый мужской вокал', 'laid-back soulful male vocals'],
    ['низкий резонирующий бас-вокал', 'low resonant bass vocals'],
    ['оперное женское сопрано', 'operatic female soprano'],
    ['рэп-флоу, ритмичная подача', 'rap flow, rhythmic delivery'],
    ['крик и гроул', 'screamed and growled male vocals'],
    ['выкрикнутый отчаянный мужской вокал', 'shouted desperate male vocals'],
    ['пронзительный женский вокал', 'shrill female vocals'],
    ['гладкое мужское напевание, крунинг', 'smooth crooning male vocals'],
    ['парящий мощный женский вокал', 'soaring powerful female vocals'],
    ['мужской вокал рассказчика, драматичная подача, подпевающий хор', 'storytelling male vocals with dramatic delivery, singalong gang chorus'],
    ['дерзкий мужской баритон', 'swaggering baritone male vocals'],
    ['горловое пение, обертоны', 'throat singing overtone drones'],
    ['вокодерный робо-вокал', 'vocoder robot vocals'],
    ['тёплый интимный женский вокал', 'warm intimate female vocals'],
    ['тёплый интимный мужской вокал', 'warm intimate male vocals'],
    ['усталый надтреснутый низкий голос с мукой, полуречитатив, в грязи', 'weary strained low male voice cracking with anguish, half-spoken, buried in mud'],
    ['шёпотный спокен-ворд поверх саундскейпа', 'whispered spoken-word male recitation over soundscape'],
    ['шёпотный женский вокал, близкий микрофон', 'whispered female vocals, close-miked'],
  ],
  mood: [
    ['грустно, тоска', 'melancholy, sadness'],
    ['светло и спокойно', 'serene, warm, peaceful'],
    ['страшно, тревожно', 'dark, unsettling'],
    ['драйв, энергия', 'energetic, driving'],
    ['мечтательно, как в тумане', 'dreamy, hazy'],
    ['торжественно, масштабно', 'triumphant, majestic'],
    ['весело, праздник', 'joyful, celebratory'],
    ['романтично', 'romantic longing'],
    ['абразивно, срочно, энергично', 'abrasive, urgent, energetic'],
    ['гимново-триумфально', 'anthemic triumphant'],
    ['атмосферно, смурно', 'atmospheric, moody'],
    ['горько-сладкая ностальгия', 'bittersweet nostalgia'],
    ['мрачно, свирепо и срочно', 'bleak fierce and urgent'],
    ['пост-советская безнадёга', 'bleak post-soviet hopelessness'],
    ['кабаре-театр, гипнотическая мрачность', 'cabaret theatre mood, hypnotic brooding'],
    ['празднично, вечеринка', 'celebratory party'],
    ['кинематографично', 'cinematic'],
    ['клаустрофобический ужас', 'claustrophobic dread'],
    ['космическое удивление', 'cosmic wonder'],
    ['циничная ирония', 'cynical irony'],
    ['атмосфера тёмной сказки', 'dark fairy tale atmosphere'],
    ['мечтательная меланхолия', 'dreamy melancholy'],
    ['жутко, тревожно', 'eerie unsettling'],
    ['эпический размах', 'epic grandeur'],
    ['нежная элегия, плач', 'gentle lament, elegiac'],
    ['надежда, рассвет', 'hopeful sunrise'],
    ['гипнотический транс-повтор', 'hypnotic trance-like repetition'],
    ['интенсивная агрессия', 'intense aggression'],
    ['одинокая полночь', 'lonely midnight'],
    ['медитативная духовная баллада', 'meditative spiritual ballad'],
    ['коварная игривость', 'mischievous playful'],
    ['монотонное безысходное отчаяние, без яркой мелодии, серость', 'monotonous hopeless despair, no bright melody, grey atmosphere'],
    ['нервная паранойя', 'nervous paranoia'],
    ['без цепкой мелодии, мрачная безнадёга', 'no catchy melody, bleak hopelessness'],
    ['без крика', 'no shouting'],
    ['параноидальная клаустрофобия', 'paranoid claustrophobia'],
    ['игривый абсурд', 'playful absurdity'],
    ['бунтарская дерзость', 'rebellious defiance'],
    ['романтическая тоска', 'romantic longing'],
    ['саркастичный деп-пан', 'sarcastic deadpan'],
    ['простая счастливая поп-мелодия, вечеринка', 'simple happy pop melody, party'],
    ['солнечное утро', 'sunny morning'],
    ['уверенная расхлябанность', 'swaggering confidence'],
    ['нежная колыбельная', 'tender lullaby'],
    ['триумфальная эпика', 'triumphant epic'],
    ['усталая покорность', 'weary resignation'],
    ['грустное странничество', 'wistful wanderlust'],
  ],
  production: [
    ['чисто, как на хорошей студии', 'clean studio production'],
    ['шум плёнки, старая запись', 'vintage tape recording, hiss'],
    ['как живой концерт в клубе', 'live club recording'],
    ['громко и плотно, современно', 'modern loud polished mix'],
    ['сыро и грязно, как в гараже', 'raw lo-fi garage recording'],
    ['просторно, много эха', 'spacious wide stereo, cavernous reverb'],
    ['домашняя запись 1987, лоу-фай муть', '1987 home tape recording, lo-fi murk'],
    ['сибирский магнитиздат 1988, ленту в хрипе и промышленном хаосе', '1988 Siberian underground home-tape recording, lo-fi tape murk with noisy industrial chaos'],
    ['AM-радио компрессия', 'AM radio compression'],
    ['взорванная кассетная муть, вобл и шипение ленты', 'blown-out cassette murk, tape wobble and hiss'],
    ['яркий современный поп-лоск', 'bright modern pop sheen'],
    ['соборный реверб, огромное пространство', 'cathedral reverb, huge space'],
    ['чистая современная студия', 'clean modern studio'],
    ['сжатый радио-звук', 'compressed radio sound'],
    ['хрустящий телефонный EQ', 'crunchy telephone EQ'],
    ['плотная стена звука', 'dense wall of sound'],
    ['сухая близкая ясность', 'dry close-miked clarity'],
    ['даб-микшение, эхо и выпадения', 'dub mixing, echoes and dropouts'],
    ['гараж-репетиционка', 'garage rehearsal room ambience'],
    ['зернистое аналоговое тепло', 'gritty analog warmth'],
    ['8-битный бит-краш', 'lo-fi 8-bit bitcrushed chip sound'],
    ['лоу-фай кассетная запись', 'lo-fi cassette recording'],
    ['лоу-фай домашняя муть', 'lo-fi home-tape murk'],
    ['лоу-фай запись с телефона', 'lo-fi phone recording'],
    ['вой громкости, кирпич', 'loudness war brickwall'],
    ['глухо, как под одеялами', 'muffled under blankets'],
    ['узкое моно', 'narrow mono'],
    ['полированный радио-микс', 'polished radio-ready mix'],
    ['просторный широкий стерео', 'spacious wide stereo'],
    ['ленточное насыщение, холодный сырой подвал', 'tape saturation, cold damp basement recording'],
    ['запись 1930-х', 'vintage 1930s recording'],
    ['винтажная аналоговая запись', 'vintage analog recording'],
    ['гараж 1960-х', '1960s garage recording, vintage analog'],
    ['сырой гранж 1991', '1991 raw grunge production'],
    ['аналоговое регги 1977', '1977 analog reggae production'],
    ['тёплый винил', 'warm vinyl character'],
  ],
}
// ru → en словарь по всем полям (для подстановки при отправке)
export const slotDict = {}
for (const opts of Object.values(slotOptions)) {
  for (const [ru, en] of opts) slotDict[ru.trim().toLowerCase()] = en
}

// в подсказках — по-русски, по алфавиту
export const slotHints = {}
for (const [k, opts] of Object.entries(slotOptions)) {
  slotHints[k] = [...opts].sort((a, b) => a[0].localeCompare(b[0], 'ru'))
}

export const durOptions = [
  { id: 'auto', n: 1 },
  { id: 's1', n: 3 },
  { id: 's2', n: 8 },
  { id: 's3', n: 16 },
  { id: 's4', n: 36 },
]

// жёсткий потолок семантических токенов для режима длительности (~25 т/с):
// «1–2 мин» → не дальше ~3000 токенов, сколько бы модель ни хотела
export const durTokens = {
  auto: 0,
  s1: 3000,    // ~1–2 мин
  s2: 7500,    // ~2–5 мин
  s3: 15000,   // ~5–10 мин
  s4: 16000,   // ~10 мин; дальше — потолок VRAM 16 ГБ (YUE2_MAX_TOKENS)
}

export const odPartyChips = [
  { ru: 'чистая гитара (арпеджио)', en: 'clean arpeggiated guitar' },
  { ru: 'гитара с фуззом', en: 'fuzz lead guitar' },
  { ru: 'акустика (перебор)', en: 'fingerpicked acoustic guitar' },
  { ru: 'пиано', en: 'soft piano comping' },
  { ru: 'орган', en: 'Hammond organ pads' },
  { ru: 'синт-подклад', en: 'warm synth pad' },
  { ru: 'струнные', en: 'lush string section' },
  { ru: 'флейта', en: 'airy flute melody' },
  { ru: 'сакс', en: 'smooth saxophone lines' },
  { ru: 'труба', en: 'muted trumpet phrases' },
  { ru: 'колокольчики', en: 'sparse glockenspiel' },
  { ru: 'перкуссия', en: 'gentle percussion layer' },
  { ru: 'бэк-вокал (хор)', en: 'distant choir backing vocals' },
]
